//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practica04_FNavas.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class pruebaModel : DbContext
    {
        public pruebaModel()
            : base("name=pruebaModel")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<autor> autor { get; set; }
        public virtual DbSet<autorLibro> autorLibro { get; set; }
        public virtual DbSet<editorial> editorial { get; set; }
        public virtual DbSet<libro> libro { get; set; }
        public virtual DbSet<Pais> Pais { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
